stages:
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ${CICD_GIT_REPO_NAME}:qa-${CICD_GIT_COMMIT}
      pushRemote: true
      registry: 463105524027.dkr.ecr.us-east-1.amazonaws.com/regional
notification: {}
