stages:
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: imed-cl/${CICD_GIT_REPO_NAME}:qa-${CICD_GIT_COMMIT}
      pushRemote: true
      registry: gcr.io
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/deployment.yaml
notification: {}
