stages:
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ${CICD_GIT_REPO_NAME}:qa-${CICD_GIT_COMMIT}
      pushRemote: true
      registry: gcr.io/imed-cl/
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/deployment.yaml
notification: {}
